(defun erl-new-file (module-name tpl-file)
  (setq new-file (format "%s.erl" module-name))
  (copy-file tpl-file new-file)
  (switch-to-buffer (find-file new-file))
  (search-forward "(")
  (setq begin (point))
  (search-forward ")")
  (backward-char)
  (kill-region begin (point))
  (insert module-name))

(defun erl-new-module (module-name)
  (interactive "MModule name:")
  (erl-new-file module-name "~/.emacs.d/tpl/module_tpl.erl"))

(defun erl-new-supervisor (module-name)
  (interactive "MModule name:")
  (erl-new-file module-name "~/.emacs.d/tpl/supervisor_tpl.erl"))

(defun erl-new-gen-server (module-name)
  (interactive "MModule name:")
  (erl-new-file module-name "~/.emacs.d/tpl/gen_server_tpl.erl"))

(defun clone-line-at-point ()
  (kill-region (line-beginning-position) (+ 1 (line-end-position)))
  (yank)
  (yank))

(defun erl-spec ()
  (interactive)
  (clone-line-at-point)
  (previous-line 2)
  (beginning-of-line)
  (insert "-spec(")
  (skip-chars-forward "^(")
  (forward-char)
  (delete-region (point) (line-end-position)))
(global-set-key (kbd "C-c C-s") 'erl-spec)

(defun erl-gen-server-call ()
  (interactive)
  (clone-line-at-point)
  (previous-line)
  (beginning-of-line)
  (insert "    gen_server:call(?MODULE, {")
  (skip-chars-forward "^(")
  (delete-char 1)
  (insert ", ")
  (skip-chars-forward "^)")
  (delete-region (point) (line-end-position))
  (insert "}).")
  (skip-chars-backward "^}")
  (setq p1 (point))
  (skip-chars-backward "^{")
  (backward-char)
  (setq p2 (point))
  (kill-ring-save p2 p1)
  (end-of-line)
  (newline 2)
  (insert "handle_call(")
  (yank)
  (insert ", _From, State) ->")
  (newline)
  (insert "    {reply, Reply, State};")
  (previous-line)
  (beginning-of-line))
(global-set-key (kbd "C-c C-g") 'erl-gen-server-call)

(defun erl-gen-server-cast ()
  (interactive)
  (clone-line-at-point)
  (previous-line)
  (beginning-of-line)
  (insert "    gen_server:cast(?MODULE, {")
  (skip-chars-forward "^(")
  (delete-char 1)
  (insert ", ")
  (skip-chars-forward "^)")
  (delete-region (point) (line-end-position))
  (insert "}), ok.")
  (skip-chars-backward "^}")
  (setq p1 (point))
  (skip-chars-backward "^{")
  (backward-char)
  (setq p2 (point))
  (kill-ring-save p2 p1)
  (end-of-line)
  (newline 2)
  (insert "handle_cast(")
  (yank)
  (insert ", State) ->")
  (newline)
  (insert "    {noreply, State};")
  (previous-line)
  (beginning-of-line))
(global-set-key (kbd "C-c M-g") 'erl-gen-server-cast)


